name: CD to HTW server

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Deploy the Discord bot
    runs-on: ubuntu-latest

    steps:

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Deploy to production
      uses: easingthemes/ssh-deploy@v2.1.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}

    - name: Restart service
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ${{ secrets.REMOTE_TARGET }}
          docker-compose restart
